name: Run Web Scraper

on:
    schedule:
        # Schedule the script to run at 00:00 UTC every day
        - cron: "0 0 * * *"

jobs:
  scrape_job_offers:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # Use the Python version you're working with

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the scraper script
    - name: Run scraper
      run: python scraper.py

    # Send email notification
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        # Update the following with your email settings
        server_address: smtp.your-email-provider.com
        server_port: 587  # Common ports: 587 (TLS), 465 (SSL), or 25
        username: ${{ secrets.EMAIL_USERNAME }}  # Add your email as a secret in GitHub
        password: ${{ secrets.EMAIL_PASSWORD }}  # Add your email password as a secret in GitHub
        subject: New Job Offer Alert
        body: A new job offer has been detected. Check your repository for details.
        to: your-email@example.com  # Replace with your email
        from: your-email@example.com  # Replace with your email
